# Загрузка и подготовка данных

In [2]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

Загрузим и обработаем данные

In [3]:
energy_df = pd.DataFrame
energy_df = pd.read_csv('../data/energy_efficiency_preprocessed.csv' )
energy_df.head()

Unnamed: 0  Compactness  S_Surface  ...  Glass_3  Glass_4  Glass_5
0           0         0.98      514.5  ...        0        0        0
1           1         0.98      514.5  ...        0        0        0
2           2         0.98      514.5  ...        0        0        0
3           3         0.98      514.5  ...        0        0        0
4           4         0.90      563.5  ...        0        0        0

[5 rows x 19 columns]

In [4]:
del energy_df['Unnamed: 0']

In [5]:
energy_df

Compactness  S_Surface  S_Wall  S_Roof  ...  Glass_2  Glass_3  Glass_4  Glass_5
0           0.98      514.5   294.0  110.25  ...        0        0        0        0
1           0.98      514.5   294.0  110.25  ...        0        0        0        0
2           0.98      514.5   294.0  110.25  ...        0        0        0        0
3           0.98      514.5   294.0  110.25  ...        0        0        0        0
4           0.90      563.5   318.5  122.50  ...        0        0        0        0
..           ...        ...     ...     ...  ...      ...      ...      ...      ...
763         0.64      784.0   343.0  220.50  ...        0        0        0        1
764         0.62      808.5   367.5  220.50  ...        0        0        0        1
765         0.62      808.5   367.5  220.50  ...        0        0        0        1
766         0.62      808.5   367.5  220.50  ...        0        0        0        1
767         0.62      808.5   367.5  220.50  ...        0        0        0        1

[768 rows x 18 columns]

In [6]:
 energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Compactness     768 non-null    float64
 1   S_Surface       768 non-null    float64
 2   S_Wall          768 non-null    float64
 3   S_Roof          768 non-null    float64
 4   Overall_Height  768 non-null    int64  
 5   S_Glazing       768 non-null    float64
 6   Heating Load    768 non-null    float64
 7   Cooling Load    768 non-null    float64
 8   Orientation_2   768 non-null    int64  
 9   Orientation_3   768 non-null    int64  
 10  Orientation_4   768 non-null    int64  
 11  Orientation_5   768 non-null    int64  
 12  Glass_0         768 non-null    int64  
 13  Glass_1         768 non-null    int64  
 14  Glass_2         768 non-null    int64  
 15  Glass_3         768 non-null    int64  
 16  Glass_4         768 non-null    int64  
 17  Glass_5         768 non-null    int

Разобьем датасет на обучающую и тестовую выборки. Предсказывать будем столбец Heating Load.

In [7]:
X = energy_df.iloc[:, : 6].join(energy_df.iloc[:, 8:]).values
y = energy_df.iloc[:, 6].values
print(X)

[[9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [6.200e-01 8.085e+02 3.675e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 0.000e+00 0.000e+00 1.000e+00]]


In [8]:
print(y)

[15.55 15.55 15.55 15.55 20.84 21.46 20.71 19.68 19.5  19.95 19.34 18.31
 17.05 17.41 16.95 15.98 28.52 29.9  29.63 28.75 24.77 23.93 24.77 23.93
  6.07  6.05  6.01  6.04  6.37  6.4   6.37  6.4   6.85  6.79  6.77  6.81
  7.18  7.1   7.1   7.1  10.85 10.54 10.77 10.56  8.6   8.49  8.45  8.5
 24.58 24.63 24.63 24.59 29.03 29.87 29.14 28.09 26.28 26.91 26.37 25.27
 23.53 24.03 23.54 22.58 35.56 37.12 36.9  35.94 32.96 32.12 32.94 32.21
 10.36 10.43 10.36 10.39 10.71 10.8  10.7  10.75 11.11 11.13 11.09 11.16
 11.68 11.69 11.7  11.69 15.41 15.2  15.42 15.21 12.96 12.97 12.93 13.02
 24.29 24.31 24.13 24.25 28.88 29.68 28.83 27.9  26.48 27.02 26.33 25.36
 23.75 24.23 23.67 22.79 35.65 37.26 36.97 36.03 33.16 32.4  33.12 32.41
 10.42 10.46 10.32 10.45 10.64 10.72 10.55 10.68 11.45 11.46 11.32 11.49
 11.45 11.42 11.33 11.43 15.41 15.18 15.34 15.19 12.88 13.   12.97 13.04
 24.28 24.4  24.11 24.35 28.07 29.01 29.62 29.05 25.41 26.47 26.89 26.46
 22.93 23.84 24.17 23.87 35.78 35.48 36.97 36.7  32.

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

X_train

array([[6.200e-01, 8.085e+02, 3.675e+02, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [6.600e-01, 7.595e+02, 3.185e+02, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [7.400e-01, 6.860e+02, 2.450e+02, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [7.100e-01, 7.105e+02, 2.695e+02, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [6.600e-01, 7.595e+02, 3.185e+02, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

Масштабируем данные.

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-1.35049563,  1.53607943,  1.20066368, ..., -0.51045409,
        -0.49300665,  2.14330352],
       [-0.97930374,  0.98871735,  0.0399861 , ..., -0.51045409,
        -0.49300665, -0.46656947],
       [-0.23691996,  0.16767423, -1.70103028, ..., -0.51045409,
        -0.49300665, -0.46656947],
       ...,
       [-0.51531388,  0.44135527, -1.12069149, ..., -0.51045409,
         2.02837021, -0.46656947],
       [ 1.99023137, -1.74809304, -0.54035269, ...,  1.95904003,
        -0.49300665, -0.46656947],
       [-0.97930374,  0.98871735,  0.0399861 , ..., -0.51045409,
        -0.49300665, -0.46656947]])

# Regression

## Линейная регрессия

Ссылка: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

In [11]:
from sklearn.linear_model import LinearRegression
lreg = LinearRegression().fit(X_train, y_train)
y_pred = lreg.predict(X_test)

model_score = lreg.score(X_test,y_test)
r_square = metrics.r2_score(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)


print("Model Score            : ", model_score)
print("R Square               : ", r_square)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.9231303855680261
R Square               :  0.9231303855680261
Mean Squared Error     :  8.229924585838194
Root Mean Squared Error:  2.8687845136639654
Mean Absolute Error    :  2.0779769416513556


## Регрессия дерева решений




Ссылка: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html

Подберем гиперпараметр максимальную глубину дерева. 

In [ ]:
from sklearn.tree import DecisionTreeRegressor

clf = GridSearchCV(DecisionTreeRegressor(), {'max_depth': range(2,10,1)})

clf.fit(X_train, y_train)

clf.best_params_

{'max_depth': 7}

In [ ]:
dtr = DecisionTreeRegressor(max_depth=7).fit(X_train, y_train)
y_pred = dtr.predict(X_test)


model_score = dtr.score(X_test,y_test)
r_square = metrics.r2_score(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)

print("Model Score            : ", model_score)
print("R Square               : ", r_square)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.9971331659818846
R Square               :  0.9971331659818846
Mean Squared Error     :  0.31929375082776457
Root Mean Squared Error:  0.5650608381650285
Mean Absolute Error    :  0.3964787541462867


## LASSO

Ссылка: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html

In [ ]:
from sklearn.linear_model import Lasso
ls = Lasso().fit(X_train, y_train)
y_pred = ls.predict(X_test)

model_score = ls.score(X_test,y_test)
r_square = metrics.r2_score(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)


print("Model Score            : ", model_score)
print("R Square               : ", r_square)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.8820178055965955
R Square               :  0.8820178055965955
Mean Squared Error     :  13.140271513422979
Root Mean Squared Error:  3.6249512429028585
Mean Absolute Error    :  2.7257425220758167


## Гребневая регрессия

Ссылка: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html

In [ ]:
from sklearn.linear_model import Ridge
Rid = Ridge().fit(X_train, y_train)
y_pred = Rid.predict(X_test)

model_score = Rid.score(X_test,y_test)
r_square = metrics.r2_score(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)


print("Model Score            : ", model_score)
print("R Square               : ", r_square)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.9241596082958602
R Square               :  0.9241596082958603
Mean Squared Error     :  8.446726590533649
Root Mean Squared Error:  2.9063252726654065
Mean Absolute Error    :  2.062367362456845


## Elastic Net регрессия

Ссылка: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html

In [ ]:
from sklearn.linear_model import ElasticNet
Rln = ElasticNet().fit(X_train, y_train)
y_pred = Rln.predict(X_test)

model_score = Rln.score(X_test,y_test)
r_square = metrics.r2_score(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)


print("Model Score            : ", model_score)
print("R Square               : ", r_square)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.8330996999131024
R Square               :  0.8330996999131023
Mean Squared Error     :  18.58852744605608
Root Mean Squared Error:  4.311441458034201
Mean Absolute Error    :  3.3473818892635228


# Выводы по регрессии

Анализируя метрики ошибок можно увидеть что наилучшее предсказание дал алгоритм дерево решений.

Линейная и гребневая регрессия при высоком значении коэффицента детерминации (R^2 Square) дали не такую высокую среднюю абсолютную ошибку (Mean Absolute Error), однако уступают дереву решений.

Алгоритмы LASSO и Elastic Net регрессии дали наихудшие значения коэффицента детерминации из представленных алгоритмов. Они так же имеют высокие значения среднеквадратичной ошибки, чувствительной к выбросам.