# Загрузка и подготовка данных

In [94]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import ensemble

In [95]:
wcd_df = pd.DataFrame
wcd_df = pd.read_csv('../data/wholesale_customers_data_preprocessed.csv' )
wcd_df.head()

Unnamed: 0  Channel  Fresh  ...  Region_Lisbon  Region_Oporto  Other Region
0           0        1  12669  ...              0              0             1
1           1        1   7057  ...              0              0             1
2           2        1   6353  ...              0              0             1
3           3        0  13265  ...              0              0             1
4           4        1  22615  ...              0              0             1

[5 rows x 11 columns]

In [96]:
del wcd_df['Unnamed: 0']

In [97]:
wcd_df

Channel  Fresh   Milk  ...  Region_Lisbon  Region_Oporto  Other Region
0          1  12669   9656  ...              0              0             1
1          1   7057   9810  ...              0              0             1
2          1   6353   8808  ...              0              0             1
3          0  13265   1196  ...              0              0             1
4          1  22615   5410  ...              0              0             1
..       ...    ...    ...  ...            ...            ...           ...
435        0  29703  12051  ...              0              0             1
436        0  39228   1431  ...              0              0             1
437        1  14531  15488  ...              0              0             1
438        0  10290   1981  ...              0              0             1
439        0   2787   1698  ...              0              0             1

[440 rows x 10 columns]

Будем делить на классы по параметру Channel (оптовая или розничная продажа продуктов)

In [98]:
wcd_df['Channel'].unique()

array([1, 0])

In [99]:
X = wcd_df.iloc[:, 1: ].values
y = wcd_df.iloc[:, 0].values
print(X)

[[12669  9656  7561 ...     0     0     1]
 [ 7057  9810  9568 ...     0     0     1]
 [ 6353  8808  7684 ...     0     0     1]
 ...
 [14531 15488 30243 ...     0     0     1]
 [10290  1981  2232 ...     0     0     1]
 [ 2787  1698  2510 ...     0     0     1]]


In [100]:
print(y)

[1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 0
 1 1 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 1
 1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 1 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0
 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1
 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 1 1 1 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]


Разобьем датасет на обучение и тестовые данные, масштабируем данные.

In [101]:
from sklearn.model_selection import train_test_split
from collections import Counter

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, stratify=y)

print(Counter(y_train).values())
print(Counter(y_test).values())

dict_values([238, 114])
dict_values([60, 28])


In [102]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [103]:
X_train

array([[ 5.73099692e-01, -5.39862051e-01, -6.80649028e-01, ...,
        -4.48737326e-01, -3.37526370e-01,  6.07988327e-01],
       [ 1.14649312e+00,  3.98571182e+00,  1.53104503e+00, ...,
        -4.48737326e-01, -3.37526370e-01,  6.07988327e-01],
       [-7.98827266e-02,  3.08118711e-03, -2.50823707e-01, ...,
         2.22847520e+00, -3.37526370e-01, -1.64476842e+00],
       ...,
       [-1.33342807e-01, -5.71792191e-01, -7.41695738e-01, ...,
        -4.48737326e-01, -3.37526370e-01,  6.07988327e-01],
       [-1.04408640e-01, -6.26884768e-01, -6.36221797e-01, ...,
        -4.48737326e-01, -3.37526370e-01,  6.07988327e-01],
       [ 7.37727885e-01, -5.17223058e-01, -1.49260230e-01, ...,
        -4.48737326e-01,  2.96273147e+00, -1.64476842e+00]])

# Композиции алгоритмов

In [104]:
from sklearn.model_selection import GridSearchCV

## Бэггинг

In [109]:
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB

In [110]:
%%time
clf = GaussianNB()
bgc = BaggingClassifier(clf)

bagging_parameters = {'n_estimators' : range(10, 50, 10), 'max_features' : range(1,5,1)}
bagging = GridSearchCV(bgc, bagging_parameters)
bagging.fit(X_train, y_train)

CPU times: user 3.5 s, sys: 43.9 ms, total: 3.54 s
Wall time: 3.6 s


In [111]:
bagging.best_params_

{'max_features': 4, 'n_estimators': 10}

In [113]:
y_pred = bagging.predict(X_test)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[58  2]
 [ 5 23]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.94        60
           1       0.92      0.82      0.87        28

    accuracy                           0.92        88
   macro avg       0.92      0.89      0.91        88
weighted avg       0.92      0.92      0.92        88



## Бустинг

In [114]:
from sklearn.ensemble import GradientBoostingClassifier

In [115]:
%%time
gbc = GradientBoostingClassifier()
boosting_parameters = {'n_estimators' : range(5,20,5), 'max_depth' : range(1,8,1)}
boosting = GridSearchCV(gbc, boosting_parameters)
boosting.fit(X_train, y_train)

CPU times: user 1.77 s, sys: 4.24 ms, total: 1.77 s
Wall time: 1.8 s


In [116]:
boosting.best_params_

{'max_depth': 2, 'n_estimators': 10}

In [117]:
y_pred = boosting.predict(X_test)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[57  3]
 [ 4 24]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94        60
           1       0.89      0.86      0.87        28

    accuracy                           0.92        88
   macro avg       0.91      0.90      0.91        88
weighted avg       0.92      0.92      0.92        88



## Стекинг

In [124]:
from sklearn.ensemble import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier

Подберем гиперпараметры к алгоритму KNeighborsClassifier

In [125]:
knc_parameters = {'n_neighbors': range(1, 10, 1)}

knc = KNeighborsClassifier()
clf_knc = GridSearchCV(knc, knc_parameters)

clf_knc.fit(X_train, y_train)
clf_knc.best_params_

{'n_neighbors': 8}

In [126]:
%%time
estimators = [
('gnb', GaussianNB()),
('knn', KNeighborsClassifier(n_neighbors = 8))]

sc = StackingClassifier(estimators=estimators)
sc.fit(X_train, y_train)
y_pred = sc.predict(X_test)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[56  4]
 [ 7 21]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91        60
           1       0.84      0.75      0.79        28

    accuracy                           0.88        88
   macro avg       0.86      0.84      0.85        88
weighted avg       0.87      0.88      0.87        88

CPU times: user 34.4 ms, sys: 1 ms, total: 35.4 ms
Wall time: 36.8 ms


# Выводы

Алгоритмы беггинг и бустинг отраболи примерно одинаково с достаточно высокими значениями полноты и точности, ошибившись лишь на 7 объектах из выборки.

Алгоритм стекинг дал результат чуть хуже, ошибившись уже на 11 объектах из выборки.