# Загрузка и подготовка данных

In [56]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import ensemble

In [57]:
energy_df = pd.DataFrame
energy_df = pd.read_csv('../data/energy_efficiency_preprocessed.csv' )
energy_df.head()

Unnamed: 0  Compactness  S_Surface  ...  Glass_3  Glass_4  Glass_5
0           0         0.98      514.5  ...        0        0        0
1           1         0.98      514.5  ...        0        0        0
2           2         0.98      514.5  ...        0        0        0
3           3         0.98      514.5  ...        0        0        0
4           4         0.90      563.5  ...        0        0        0

[5 rows x 19 columns]

In [58]:
del energy_df['Unnamed: 0']

In [59]:
energy_df

Compactness  S_Surface  S_Wall  S_Roof  ...  Glass_2  Glass_3  Glass_4  Glass_5
0           0.98      514.5   294.0  110.25  ...        0        0        0        0
1           0.98      514.5   294.0  110.25  ...        0        0        0        0
2           0.98      514.5   294.0  110.25  ...        0        0        0        0
3           0.98      514.5   294.0  110.25  ...        0        0        0        0
4           0.90      563.5   318.5  122.50  ...        0        0        0        0
..           ...        ...     ...     ...  ...      ...      ...      ...      ...
763         0.64      784.0   343.0  220.50  ...        0        0        0        1
764         0.62      808.5   367.5  220.50  ...        0        0        0        1
765         0.62      808.5   367.5  220.50  ...        0        0        0        1
766         0.62      808.5   367.5  220.50  ...        0        0        0        1
767         0.62      808.5   367.5  220.50  ...        0        0        0        1

[768 rows x 18 columns]

In [60]:
 energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Compactness     768 non-null    float64
 1   S_Surface       768 non-null    float64
 2   S_Wall          768 non-null    float64
 3   S_Roof          768 non-null    float64
 4   Overall_Height  768 non-null    int64  
 5   S_Glazing       768 non-null    float64
 6   Heating Load    768 non-null    float64
 7   Cooling Load    768 non-null    float64
 8   Orientation_2   768 non-null    int64  
 9   Orientation_3   768 non-null    int64  
 10  Orientation_4   768 non-null    int64  
 11  Orientation_5   768 non-null    int64  
 12  Glass_0         768 non-null    int64  
 13  Glass_1         768 non-null    int64  
 14  Glass_2         768 non-null    int64  
 15  Glass_3         768 non-null    int64  
 16  Glass_4         768 non-null    int64  
 17  Glass_5         768 non-null    int

Разобьем датасет на обучающую и тестовую выборки. Предсказывать будем столбец Heating Load.

In [61]:
X = energy_df.iloc[:, : 6].join(energy_df.iloc[:, 8:]).values
y = energy_df.iloc[:, 6].values
print(X)

[[9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [6.200e-01 8.085e+02 3.675e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 0.000e+00 0.000e+00 1.000e+00]]


In [62]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

X_train

array([[6.900e-01, 7.350e+02, 2.940e+02, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [8.200e-01, 6.125e+02, 3.185e+02, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [6.600e-01, 7.595e+02, 3.185e+02, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [7.100e-01, 7.105e+02, 2.695e+02, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [6.600e-01, 7.595e+02, 3.185e+02, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [7.900e-01, 6.370e+02, 3.430e+02, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

Масштабируем данные.

In [63]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.67751125,  0.6911543 , -0.59248944, ..., -0.49592305,
         2.15699596, -0.48716238],
       [ 0.54970879, -0.6927005 , -0.0140043 , ..., -0.49592305,
        -0.46360773,  2.05270364],
       [-0.96071588,  0.96792526, -0.0140043 , ...,  2.01644185,
        -0.46360773, -0.48716238],
       ...,
       [-0.48870817,  0.41438334, -1.17097458, ..., -0.49592305,
         2.15699596, -0.48716238],
       [-0.96071588,  0.96792526, -0.0140043 , ..., -0.49592305,
         2.15699596, -0.48716238],
       [ 0.26650417, -0.41592954,  0.56448084, ..., -0.49592305,
        -0.46360773, -0.48716238]])

# Композиции алгоритмов

In [22]:
from sklearn.model_selection import GridSearchCV

## Бэггинг

In [35]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor

In [36]:
clf = GridSearchCV(DecisionTreeRegressor(), {'max_depth': range(2,10,1)})
clf.fit(X_train, y_train)
clf.best_params_

{'max_depth': 7}

In [37]:
%%time
dtr = DecisionTreeRegressor(max_depth=7)
bgc = BaggingRegressor(dtr)

bagging_parameters = {'n_estimators' : range(10, 50, 10), 'max_features' : range(1,5,1)}
bagging = GridSearchCV(bgc, bagging_parameters)
bagging.fit(X_train, y_train)

CPU times: user 3.32 s, sys: 35.5 ms, total: 3.35 s
Wall time: 3.34 s


In [38]:
bagging.best_params_

{'max_features': 4, 'n_estimators': 10}

In [39]:
y_pred = bagging.predict(X_test)

model_score = bagging.score(X_test,y_test)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)

print("Model Score            : ", model_score)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.8563932506151329
Mean Squared Error     :  13.860465676091266
Root Mean Squared Error:  3.7229646353532915
Mean Absolute Error    :  3.0179399804379465


## Бустинг

In [44]:
from sklearn.ensemble import GradientBoostingRegressor

In [45]:
%%time
gbc = GradientBoostingRegressor()
boosting_parameters = {'n_estimators' : range(5,20,5), 'max_depth' : range(1,8,1)}
boosting = GridSearchCV(gbc, boosting_parameters)
boosting.fit(X_train, y_train)

CPU times: user 1.03 s, sys: 758 µs, total: 1.03 s
Wall time: 1.03 s


In [46]:
boosting.best_params_

{'max_depth': 7, 'n_estimators': 15}

In [47]:
y_pred = boosting.predict(X_test)

model_score = boosting.score(X_test,y_test)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)

print("Model Score            : ", model_score)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.9556663449346994
Mean Squared Error     :  4.278943064726331
Root Mean Squared Error:  2.0685606263115255
Mean Absolute Error    :  1.8475475403209058


## Стекинг

In [53]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

In [54]:
%%time
estimators = [('lreg', LinearRegression()),('Rid', Ridge())]
sr = StackingRegressor(estimators=estimators)
stacking = sr.fit(X_train, y_train)

CPU times: user 22.2 ms, sys: 0 ns, total: 22.2 ms
Wall time: 23.7 ms


In [55]:
y_pred = boosting.predict(X_test)

model_score = stacking.score(X_test,y_test)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)

print("Model Score            : ", model_score)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.9227547828306507
Mean Squared Error     :  4.278943064726331
Root Mean Squared Error:  2.0685606263115255
Mean Absolute Error    :  1.8475475403209058


# Выводы

Лучше всех отработали алгоритмы бустинг и стекинг, на которых была получена высокая точность благодаря подбору гиперпараметров.

Алгоритм бэггинг отработал хуже остальных алгоритмов. При достаточно высокой точности имеет высокое значение Mean Squared Error.