https://colab.research.google.com/drive/17KY5mr2uWJTTcPdvdyNjCxjT36HjS-FJ

In [1]:
# from numpy import loadtxt
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

# Загрузка и подготовка данных

In [2]:
wcd_df = pd.DataFrame
wcd_df = pd.read_csv('../data/wholesale_customers_data_preprocessed.csv' )
wcd_df.head()

Unnamed: 0  Channel  Fresh  ...  Region_Lisbon  Region_Oporto  Other Region
0           0        1  12669  ...              0              0             1
1           1        1   7057  ...              0              0             1
2           2        1   6353  ...              0              0             1
3           3        0  13265  ...              0              0             1
4           4        1  22615  ...              0              0             1

[5 rows x 11 columns]

In [3]:
del wcd_df['Unnamed: 0']

In [4]:
wcd_df['Channel'].unique()

array([1, 0])

In [5]:
X = wcd_df.iloc[:, 1: ].values
y = wcd_df.iloc[:, 0].values
print(X)

[[12669  9656  7561 ...     0     0     1]
 [ 7057  9810  9568 ...     0     0     1]
 [ 6353  8808  7684 ...     0     0     1]
 ...
 [14531 15488 30243 ...     0     0     1]
 [10290  1981  2232 ...     0     0     1]
 [ 2787  1698  2510 ...     0     0     1]]


In [6]:
from sklearn.model_selection import train_test_split
from collections import Counter

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, stratify=y)

print(Counter(y_train).values())
print(Counter(y_test).values())

dict_values([114, 238])
dict_values([60, 28])


In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)